version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.19.5
    steps:
      - checkout
      - run: go version
      - run: go build ./cmd/web
workflows:
  main:
    jobs:
      - build





# VS Code Extension Version: 1.0.0