version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.19.5
    steps:
      - checkout
      - run: go version
      - run: go build ./cmd/web
  test:
    docker:
      - image: cimg/go:1.19.5
    steps:
      - run: run cypress test ./cypress
workflows:
  main:
    jobs:
      - build
      - test
