version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - cypress-cache-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          key: cypress-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/Cypress
          
      - run:
          name: Cypress Test
          command: ./node_modules/.bin/cypress run 

  deploy:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - run:
          name: Authenticate with NPM
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish --access public

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

