version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.19.5
    steps:
      - run: go version
      - run:
          name: go build
          command: <<include(go.mod)>>
workflows:
  main:
    jobs:
      - build


# VS Code Extension Version: 1.0.0