version: 2.1


jobs:
  lint:
    executor: go_docker
    steps:
      - checkout
      - run:
          name: Lint the Go cmd/web
          command: gofmt -d ./cmd/web
      - run:
          name: Lint the Go pkg/
          command: gofmt -d ./pkg
  unit-tests:
    executor: machine_no_dlc
    steps:
      - checkout
      - run: mkdir /tmp/code_coverage/
      - start_container_and_verify
      - run:
          name: Run cmd/web Go unit tests with coverage
          command: go test -v ./cmd/web -coverprofile=/tmp/code_coverage/profile.out ./...
      - store_artifacts:
          path: /tmp/code_coverage/profile.out
  # code-coverage:
  #   executor: go_docker
  #   steps:
  #     - checkout
  #     - run: mkdir /tmp/code_coverage/
  #     - run:
  #         name: Run code coverage
  #         command: go test -coverprofile=/tmp/code_coverage/profile.out ./...
  #     - store_artifacts:
  #         path: /tmp/code_coverage/profile.out
  go-static-analyzer:
    executor: go_docker
    steps:
      - checkout
      - run:
          name: Run static analyzer on cmd/web
          command: go vet ./cmd/web
      - run:
          name: Run static analyzer on pgk
          command: |
                    go vet ./pkg/forms
                    go vet ./pkg/models
                    go vet ./pkg/models/mock
                    go vet ./pkg/models/mysql

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - lint
      # - code-coverage
      - go-static-analyzer
      - unit-tests:
          requires:
            - lint
            - go-static-analyzer
          filters:
            branches:
              only:
                - main

