version: 2.1


jobs:
  build:
    executor: cimg/base:2020.01 
    steps:
      - checkout
  lint:
    executor: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Lint the Go cmd/web
          command: gofmt -d ./cmd/web
      - run:
          name: Lint the Go pkg/
          command: gofmt -d ./pkg
  unit-tests:
    executor: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Run cmd/web Go unit tests
          command: go test ./cmd/web
  go-static-analyzer:
    executor: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Run static analyzer on cmd/web
          command: go vet ./cmd/web
      - run:
          name: Run static analyzer on pgk
          command: |
                    go vet ./pkg/forms
                    go vet ./pkg/models
                    go vet ./pkg/models/mock
                    go vet ./pkg/models/mysql
  run-tests:
    docker:
      - image: cimg/base:2020.01
        auth:
          username: ahmedmo23
          password: Waterbreak2323! #context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: "echo environment variables from org-global context"
          command: echo $MY_ENV_VAR
    
workflows:
  build-test:
    jobs:
      - build
      - lint
      - unit-tests
      - go-static-analyzer
      - run-tests:
          context:
            - org-global
            - my-context