version: 2.1

workflows:
  my-workflow:
    jobs:
      - run-tests:
          context:
            - org-global
            - my-context

jobs:
  run-tests:
    docker:
      - image: cimg/base:2020.01
        auth:
          username: ahmedmo23
          password: Waterbreak2323!  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: "echo environment variables from org-global context"
          command: echo $MY_ENV_VAR
    lint:
      - image: cimg/base:2020.01
        steps:
      - checkout
      - run:
          name: Lint the Go cmd/web
          command: gofmt -d ./cmd/web
      - run:
          name: Lint the Go pkg/
          command: gofmt -d ./pkg
    unit-tests:
      - image: cimg/base:2020.01
        steps:
      - checkout
      - run:
          name: Run cmd/web Go unit tests
          command: go test ./cmd/web
    
